### PR TITLE
Transpile sources to ES5

### LINKED ISSUE #15: The ES6 class syntax makes this unusable in ES5 projects
I cannot use this library in a project that's not setup to transpile ES6 sources, because of the `class` syntax.

Most notably, the [create-react-app](https://github.com/facebookincubator/create-react-app/) boilerplate used by thousands of people, expects all dependencies to be ES5 when **building**. See https://github.com/facebookincubator/create-react-app/issues/2433#issuecomment-305461337 for an explanation.

I recommend adding a build step that uses babel to transpile the sources to ES5, and puts them in a /lib folder.

A quick try on [Try Babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code_lz=OQVwzgpgBGAuBOBLAxrYBuAUJ5B7AdnFPBAI4gREC8xZIiJAFMCeZWgJRZ6GxQBiECABMACgEN4keFBqt6TYADMhwgA6TpwLtgC2uYSAA2EAHQQAHmtzxYYWVGRHxYe4JESpEeKPi5diJDCUADemFAwsOKwKFAaXlCMuGoxBGAcoeERtLAg8PhQ-BAA7lC-_oEQjIkkYLhGAG4QADS0AFYQqBlUAHyZ2dk8RIiwELr2NADaALpYAxFDfCoi8dIORaXuYprejDpZA8vqO_CmBMzefvDArYyX3X0h7Z2wd_DwXFAAvvvzUEerbxnfDMEjiYTiABGJhuiQe_T-UBMfBGYywB3mxQAFogTIxUboHACTqYwcI9hkngSwKY1OAsfjRrpPl9sIicnkCtS5vMfui_vJ2KYAOYQV7JVKEDgYgbAi7vGywt4fWSPZ6oZUs6Xs2mINRVYleD4y7Jy4AQfDCJXwp4kXL5Wh1RpValankRPlZVlfdBAA) showed that the code was plug and play, and everything worked when pasting the transpiled code into the `feedparser-promised` module.

It looks like you tried to convert everything to es5 in this commit https://github.com/alabeduarte/feedparser-promised/commit/f8256d441ee80ae30463837759805d9b2a29cfb9 , but I don't think you succeed, maybe I'm reading the commit wrong.

I have [a fork of this for my personal usage](https://github.com/JReinhold/feedparser-promised) that fixes the issue, however I haven't tested it extensively, only with my own React project.
Let me know if you want a PR to this repo. If you see other solutions, please tell.

### PR DESCRIPTION
**Pull request by JReinhold**
Fixes #15 

It works flawlessly when using create-react-app, which was the repo that couldn't handle importing ES6 syntax.

I've added the build step to TravisCI, but I haven't tested it, since I have no experience with TravisCI.

### CODE REVIEW

**Comment by alabeduarte** [comment]
Hi @JReinhold 

Thank you for the pull request! I've noticed you pushed `lib/feedParserPromised.js` though, does it make sense? Besides, instead of having npm script "build", it shouldn't be the npm `prepublish` instead?

Check it out [the previous implementation with ES5 support using babel](https://github.com/alabeduarte/feedparser-promised/blob/1.1.1/package.json) to see if make sense what I'm saying and please let me know what do you think.

Cheers

**Comment by JReinhold** [comment]
I agree that the `lib` dir isn't necessary on the repo, but I didn't know how it would fly with npm if it was ignored, I don't have much experience with npm.

The problem with using the `prepublish`exclusively, is that it gets a little more complicated to contribute to the repo or otherwise pull directly from the repo instead of the npm. I would rather keep the `build` script to be available for humans, and the point the `prepublish` script to the `build` script. In my opinion the `prepublish`script should never be run by humans.

So, I would change:

1. .gitignore `/lib` folder.
2. update `build` script to match yours (use local babel-bin)
3. create a `prepublish` script that runs the `build` script
4. update README.md to tell contributers to run the `build` script

How does that sound?

**Comment by alabeduarte** [comment]
Hi @JReinhold 

> The problem with using the prepublish exclusively, is that it gets a little more complicated to contribute to the repo or otherwise pull directly from the repo instead of the npm.

The good thing I see about `prepublish` is that it will transpile everything after `npm install` for nodejs users. I'm assuming you use `feedparser-promised` directly from the browser, yes?

If it's true, how would be the easier way for you to use it? Maybe we could run the step `build` before the release, so it would be available [here](https://github.com/alabeduarte/feedparser-promised/releases) ready to be used, how about that?

Cheers

**Comment by JReinhold** [comment]
I'm actually using nodejs, I didn't know `prepublish` runs when users `npm install`.

I'm not quite sure how users would use this directly from the browser, but I think it's a good idea to run the `build` script before it is published as a release. Then browser-users can download the released zip file and work with that. would we need to change anything in the package.json for the `build`script to run pre-release, or is it a manual step?

**Comment by alabeduarte** [comment]
Well, since you're using through npm within node environment, I think moving to `prepublish` should be enough. Maybe we can think in a way to make this available for other usages as well.

You might take a look on this [tutorial](http://podefr.tumblr.com/post/30488475488/locally-test-your-npm-modules-without-publishing) which shows how to test npm modules without publishing, so you can try out your changes using `prepublish` and make sure everything is ok.

Let me know if you need any help!

**Comment by JReinhold** [comment]
Cool, I'll take a look at it.

**Comment by JReinhold** [comment]
It seems that `prepublish` has recently been deprecated, in favor of the identical `prepare` script: https://github.com/npm/npm/issues/10074

everything works with this setup now, tested using `pack` and inserting into another project.

EDIT: whoops, forgot Travis. will fix.

**Comment by JReinhold** [comment]
fixed Travis

**Comment by alabeduarte** [comment]
Hi @JReinhold 

Thank you for taking the considerations. I've tested here before merging and I guess we shouldn't include `/lib` directory on `.gitignore` file, otherwise it will not be included by the `prepared` script.

When I tested I got this following error:

```
module.js:487
    throw err;
    ^

Error: Cannot find module './lib/feedParserPromised'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/feedparser-promised-pull-request-test/node_modules/feedparser-promised/index.js:3:26)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

I'll list below the process that I've used to test it, maybe you could try the same to make sure it's working:

inside your codebase, run the command `npm pack`, then move out the generated `.tgz` file to *elsewhere*, eg:

## Packing

```
$ npm pack
$ mkdir ../feedparser-promised-pull-request-test
$ mv feedparser-promised-1.3.0.tgz ../feedparser-promised-pull-request-test
$ cd ../feedparser-promised-pull-request-test
```

And your file tree should look like this:

- feedparser-promised
  - src
  - test
  - node_modules
  - ...
- feedparser-promised-pull-request-test (new dir)
  - feedparser-promised-1.3.0.tgz (generated tgz file)

## Installing the local version of the package

Now, let's create a new package.json to simulate the usage of the package:

```
$ npm init
```

After setup a new package.json, now we can install the tgz file:

```
$ npm install feedparser-promised-1.3.0.tgz
```

## Testing

Create a file (eg: `test.js`) and put this code snippet below (note that I'm using ES5 sintax):

```javascript
var feedparser = require('feedparser-promised');
var url = 'http://feeds.feedwrench.com/JavaScriptJabber.rss';

feedparser.parse(url).then(function (items) {
  items.forEach(function (item) {
    console.log('title: ', item.title);
  });
}).catch(function (error) {
  console.log('error: ', error);
});
```

Then run the script and see if everything is working:

```
$ node test.js
```

If everything goes well you should see the list of podcasts from JavascriptJabber.
I hope it helps, next time I'll try to automate those steps.

Cheers

**Comment by alabeduarte** [comment]
>  I've tested here before merging and I guess we shouldn't include `/lib` directory on `.gitignore` file, otherwise it will not be included by the prepared script.

Alternatively, you might [specify](https://docs.npmjs.com/files/package.json#files) which files you wish to include in the package (eg: `node_modules`, `index.js`, `package.json` and `lib`) maybe?

**Comment by JReinhold** [comment]
Sorry for the inconvenience, I really thought I had tested it correctly. I've used your suggestion of including the `lib` folder by specifying it in the `files` array in `package.json`, and now it SHOULD work. At least it did when I followed your testing-steps (which are awesome btw, thanks).

**Comment by alabeduarte** [comment]
Hi @JReinhold 

Don't be sorry at all, it's ok!! I should say **thank you** for being so welcome to feedback and helping me with all troubleshooting.

Thank you for the contribution, you can check it out and install the version `v1.4.0` now.

Cheers!

**Pull request merged**
