### PR TITLE
Adds error handling for request and feedparser

### LINKED ISSUE #1: Errors aren't handled in the `catch`
The "Not a feed" error coming from feedparser isn't being handled with the example code. Instead of handling this gracefully, it crashes the server.

### PR DESCRIPTION
**Pull request by lynnaloo**
resolves #1

### CODE REVIEW

**Comment by troy0820** [comment]
:+1:

**Comment by wbprice** [comment]
This would be very helpful.

**Comment by alabeduarte** [comment]
Hi @lynnaloo 

Sorry by the late response, I didn't receive any github notifications about either this PR or the created issue. I'll check your PR ASAP. 

Thank you for contributing!

**Comment by lynnaloo** [comment]
No problem! I learned something fixing this as well :+1:

**Comment by alabeduarte** [comment]
Hi @lynnaloo

Looks good to me! 

Would be nice write a unit test for this code before merge this pull request. Can you do that?

You can see some examples on https://github.com/alabeduarte/feedparser-promised/blob/master/test/feedParserPromised.test.js

You can run the tests with the following command:

``` bash
$ npm test
```

Thanks!

**Comment by dsl101** [comment]
Is this still pending? I'm getting caught by this, and I see the original non-catching code in 1.0.4...

**Comment by alabeduarte** [comment]
Hi @dsl101 

The code looks great but I'd like to avoid adding a new feature without a unit test for it, that's why it's still pending. I understand that it's a simple feature but I know some people that depend on this package and I wouldn't like to risk breaking their code. Would you be interested to contribute with a few unit tests?

I could work on that but I'm not sure if I'll have time to delivery it by the next week since I'll be traveling, but I'll be super happy to merge this PR if any other person adds some test coverage for it.

Does it make sense?

Thank you!

**Comment by lynnaloo** [comment]
@alabeduarte Sorry, I've seen your comments but I just haven't had a chance to get back to this. I probably won't get back over here by next week.

**Comment by alabeduarte** [comment]
@lynnaloo @dsl101 

Added some tests and I added your PR code as well. Thank you very much.

Here is the commit: https://github.com/alabeduarte/feedparser-promised/commit/58d1f146bff62b4abb7e6025e9c802c06566cb98

**Pull request closed without merging**
